insert into "PatientEngagementKnowledgeChunk" ("id", "tenantId", "pageId", "chunkIndex", "heading", "content", "tokenEstimate", "status")
values
  ('eng_kchunk_term_scaling_root_planing', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 10, 'Scaling and root planing', 'Scaling and root planing, sometimes called a deep cleaning, is gum therapy used when buildup and inflammation extend below the gumline. Scaling removes plaque and tartar from tooth and root surfaces. Root planing smooths the root surface so the gums can heal more predictably. It is different from a routine cleaning and may be recommended after periodontal measurements, bleeding, bone loss, or gum infection concerns are reviewed by the dental team.', 74, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_periodontal_maintenance', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 11, 'Periodontal maintenance', 'Periodontal maintenance is a follow-up cleaning schedule for patients with gum disease history. It is different from a routine hygiene cleaning because the visit monitors gum pocket depths, bleeding, inflammation, bone support, and areas that previously needed deeper therapy. The dental team decides the interval based on gum health and risk.', 55, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_root_canal', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 12, 'Root canal treatment', 'A root canal treats infection or inflammation inside a tooth. The dentist or specialist removes diseased tissue from inside the tooth, cleans and seals the canals, and protects the tooth with a final restoration when appropriate. A root canal is commonly discussed when a tooth has deep decay, trauma, lingering pain, swelling, or an abscess concern.', 62, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_crown', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 13, 'Dental crown', 'A dental crown is a custom restoration that covers and protects a tooth. Crowns are commonly recommended when a tooth has a large filling, crack, root canal treatment, heavy wear, or too little natural tooth structure for a smaller repair. The process usually includes preparing the tooth, taking a scan or impression, making a temporary when needed, and placing the final crown.', 66, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_filling', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 14, 'Dental filling', 'A dental filling repairs a cavity or a small damaged area of a tooth. The dentist removes the damaged tooth structure, cleans the area, and places restorative material to rebuild the tooth shape and function. Fillings are usually discussed for smaller areas of decay or minor fractures.', 48, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_implant', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 15, 'Dental implant', 'A dental implant replaces a missing tooth root. The full process can include consultation, imaging, medical and dental review, implant placement, healing, and final restoration with a crown, bridge, or denture attachment. Timing depends on bone support, healing, medical factors, and the treatment plan created by the dentist or specialist.', 59, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_extraction', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 16, 'Tooth extraction', 'A tooth extraction removes a tooth that cannot be predictably restored or needs to be removed for another clinical reason. Extractions may be discussed for severe decay, fracture, infection, advanced gum disease, orthodontic planning, or wisdom teeth. The team should also discuss replacement options when appropriate.', 50, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_bridge', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 17, 'Dental bridge', 'A dental bridge replaces one or more missing teeth by anchoring to nearby teeth or implants. A traditional bridge uses crowns on neighboring teeth to support the replacement tooth. The dentist reviews bite, tooth support, gum health, cleanability, and alternative options before recommending a bridge.', 50, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_term_cosmetic', 'tenant_1dentalai_production', 'eng_kpage_dental_terms', 18, 'Veneers, whitening, and clear aligners', 'A veneer changes the visible front surface of a tooth, often for shape, color, spacing, or cosmetic concerns. Whitening lightens natural tooth shade but does not change the color of crowns, fillings, or veneers. Clear aligners move teeth gradually with removable trays and require a consultation to confirm the bite and tooth movement plan.', 59, 'READY_FOR_RETRIEVAL'),
  ('eng_kchunk_process_urgent_symptoms', 'tenant_1dentalai_production', 'eng_kpage_process_explanations', 10, 'Urgent dental symptom workflow', 'Urgent dental symptoms may include swelling, severe pain, trauma, uncontrolled bleeding, fever with dental infection concern, broken tooth, or a knocked-out tooth. Website chat should collect symptoms, duration, location, and callback number, then involve the dental team. If there is trouble breathing, facial swelling affecting the airway, major trauma, or uncontrolled bleeding, the visitor should seek emergency medical care immediately.', 69, 'READY_FOR_RETRIEVAL')
on conflict ("pageId", "chunkIndex") do update set
  "heading" = excluded."heading",
  "content" = excluded."content",
  "tokenEstimate" = excluded."tokenEstimate",
  "status" = excluded."status",
  "updatedAt" = current_timestamp;
